/**
 * ============================================================
 *  ESC/POS Command Builder
 *
 *  buildReceiptBytes(order, storeName, layoutConfig?) => Uint8Array
 *
 *  Text layout is generated by receiptTextRenderer.js (shared with preview).
 *  This file only handles ESC/POS byte wrapping.
 * ============================================================
 */

import { buildReceiptLines, fmtCur, fmtDate } from './receiptTextRenderer'

const ESC = 0x1B
const GS  = 0x1D
const LF  = 0x0A

const encoder = new TextEncoder()

function concat(...arrays) {
  const total = arrays.reduce((sum, a) => sum + a.length, 0)
  const result = new Uint8Array(total)
  let offset = 0
  for (const a of arrays) { result.set(a, offset); offset += a.length }
  return result
}

// ── ESC/POS Primitives ───────────────────────────────────────────────────────

export const CMD_INIT  = new Uint8Array([ESC, 0x40])
export const CMD_LF    = new Uint8Array([LF])

export function cmdFeedAndCut(lines = 3) {
  return new Uint8Array([ESC, 0x64, lines, GS, 0x56, 0x01])
}
export function cmdBold(on) {
  return new Uint8Array([ESC, 0x45, on ? 0x01 : 0x00])
}
export function cmdAlign(align) {  // 0=left  1=center  2=right
  return new Uint8Array([ESC, 0x61, align])
}
export function cmdDoubleSize(on) {
  return new Uint8Array([GS, 0x21, on ? 0x30 : 0x00])
}
export function cmdText(str) {
  return encoder.encode(str)
}
export function cmdDashedLine(width = 32, char = '-') {
  return concat(cmdText(char.repeat(width)), CMD_LF)
}

// ── Custom receipt builder ────────────────────────────────────────────────────
// Uses buildReceiptLines (same function as preview) so output is identical.

function buildCustomReceiptBytes(order, storeName, layoutConfig) {
  // Inject storeName as fallback in case order doesn't carry it
  const orderWithStore = {
    storeName:    storeName || 'Toko Saya',
    storeAddress: undefined,
    storePhone:   undefined,
    ...order,
  }

  // Get lines from the SHARED renderer (same as preview)
  const lines = buildReceiptLines(orderWithStore, layoutConfig)

  const parts = []
  const add   = (...cmds) => parts.push(...cmds)

  add(CMD_INIT)
  add(cmdAlign(0))  // left-align; centering is done in the text itself

  for (const line of lines) {
    add(cmdText(line), CMD_LF)
  }

  add(cmdFeedAndCut(4))
  return concat(...parts)
}

// ── Legacy hard-coded 32-char builder (fallback when no layoutConfig) ─────────

function buildLegacyReceiptBytes(order, tenantName) {
  const parts = []
  const add   = (...cmds) => parts.push(...cmds)
  const text  = (str) => concat(cmdText(str), CMD_LF)
  const fmt   = (n) => fmtCur(n, 'Rp', 'id-ID')
  const W     = 32

  function padLine(left, right) {
    const spaces = Math.max(1, W - left.length - right.length)
    return left + ' '.repeat(spaces) + right
  }

  add(CMD_INIT)
  add(cmdAlign(1))
  add(cmdBold(true))
  add(text(tenantName || 'Toko Saya'))
  add(cmdBold(false))
  add(cmdAlign(0))
  add(cmdDashedLine())

  add(cmdBold(true))
  add(text(`No  : ${order.order_number || '-'}`))
  add(cmdBold(false))
  add(text(`Tgl : ${fmtDate(order.created_at)}`))
  add(text(`Nama: ${order.customer_name || '-'}`))
  add(text(`Bayar: ${order.payment_method === 'cashless' ? 'QRIS' : 'Cash'}`))
  add(cmdDashedLine())

  const items = order.items || []
  items.forEach(item => {
    const right   = fmt((item.price || 0) * (item.quantity || 1))
    const label   = `${item.name} x${item.quantity}`
    const maxLeft = W - right.length - 1
    const left    = label.length > maxLeft ? label.slice(0, maxLeft - 1) + '~' : label
    add(text(padLine(left, right)))
  })
  add(cmdDashedLine())

  add(cmdBold(true))
  add(cmdAlign(2))
  add(text(`TOTAL: ${fmt(order.total_amount)}`))

  if (order.cash_paid !== undefined && order.change_amount !== undefined) {
    add(cmdBold(false))
    add(cmdDashedLine())
    add(text(`Tunai: ${fmt(order.cash_paid)}`))
    add(text(`Kembali: ${fmt(order.change_amount)}`))
  }

  add(cmdBold(false))
  add(cmdAlign(0))

  if (order.notes && order.notes !== 'POS Order') {
    add(cmdDashedLine())
    add(cmdBold(true))
    add(text(`Catatan: ${order.notes}`))
    add(cmdBold(false))
  }

  add(cmdDashedLine())
  add(cmdAlign(1))
  add(text('Terima Kasih!'))
  add(cmdAlign(0))
  add(cmdFeedAndCut(4))

  return concat(...parts)
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Build a complete receipt as a Uint8Array ready for the Bluetooth printer.
 *
 * @param {Object}  order         - Order from the API (business data, read-only)
 * @param {string}  storeName     - Tenant store name (from TenantContext/settings)
 * @param {Object}  [layoutConfig] - Layout/visibility prefs from ReceiptDesignerPage.
 *                                   null/undefined → falls back to legacy 32-char layout.
 * @returns {Uint8Array}
 */
export function buildReceiptBytes(order, storeName = 'Toko Saya', layoutConfig = null) {
  if (layoutConfig) {
    return buildCustomReceiptBytes(order, storeName, layoutConfig)
  }
  return buildLegacyReceiptBytes(order, storeName)
}
