/**
 * InsightCard — renders a Gemini insight block with bold/emoji support.
 * Props: insight (string), loading (bool), error (string), cached (bool),
 *        onRetry (fn), gradient (string CSS class), icon (emoji string)
 */
export default function InsightCard({ insight, loading, error, cached, onRetry, gradient = 'from-violet-600 to-indigo-600', icon = '🔮', title, subtitle }) {
    const renderInsight = (text) =>
        text.split('\n').filter(l => l.trim()).map((line, i) => {
            const parts = line.split(/(\*\*[^*]+\*\*)/g)
            return (
                <p key={i} className="text-sm leading-relaxed text-neutral-700">
                    {parts.map((p, j) =>
                        p.startsWith('**') && p.endsWith('**')
                            ? <strong key={j} className="font-bold text-neutral-800">{p.slice(2, -2)}</strong>
                            : p
                    )}
                </p>
            )
        })

    return (
        <div className="bg-white rounded-2xl border border-neutral-100 shadow-sm overflow-hidden">
            <div className={`bg-gradient-to-r ${gradient} p-5`}>
                <div className="flex items-center gap-3">
                    <div className="size-10 rounded-xl bg-white/20 flex items-center justify-center backdrop-blur-sm text-xl">
                        {icon}
                    </div>
                    <div>
                        <h4 className="font-bold text-white text-base">{title}</h4>
                        <p className="text-xs text-white/70">{subtitle}</p>
                    </div>
                    {cached && (
                        <span className="ml-auto text-[10px] bg-white/20 text-white px-2 py-1 rounded-lg font-medium">
                            ⚡ Cache
                        </span>
                    )}
                </div>
            </div>

            <div className="p-5">
                {loading && (
                    <div className="flex flex-col items-center gap-4 py-6">
                        <div className={`size-14 rounded-full bg-gradient-to-r ${gradient} opacity-80 flex items-center justify-center animate-pulse text-2xl`}>
                            {icon}
                        </div>
                        <p className="font-bold text-neutral-600 text-sm">Gemini sedang menganalisis...</p>
                        <div className="flex gap-1.5">
                            {[0,1,2].map(i => (
                                <div key={i} className="size-2 rounded-full bg-violet-400 animate-bounce" style={{ animationDelay: `${i*0.15}s` }} />
                            ))}
                        </div>
                    </div>
                )}

                {error && !loading && (
                    <div className="flex flex-col items-center gap-3 py-4 text-center">
                        <span className="text-3xl">😕</span>
                        <p className="text-sm text-red-500 font-bold">{error}</p>
                        {onRetry && (
                            <button onClick={onRetry} className="px-4 py-2 bg-violet-500 text-white rounded-xl text-sm font-bold hover:bg-violet-600 transition-colors">
                                Coba Lagi
                            </button>
                        )}
                    </div>
                )}

                {insight && !loading && (
                    <div className="space-y-2">
                        <div className="bg-gradient-to-br from-slate-50 to-neutral-50 rounded-xl p-4 border border-neutral-100 space-y-2">
                            {renderInsight(insight)}
                        </div>
                        <div className="flex items-center justify-between pt-1">
                            <p className="text-[10px] text-neutral-400">✨ Generated by Google Gemini</p>
                            {onRetry && (
                                <button onClick={onRetry} className="flex items-center gap-1 text-xs text-violet-500 hover:text-violet-700 font-semibold">
                                    <span className="material-symbols-outlined text-sm">refresh</span>
                                    Refresh
                                </button>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    )
}
